### PR TITLE
Add include_keys and exclude_keys to S3 sink.

### LINKED ISSUE #2975: Add include_keys and exclude_keys options under the sink
**Is your feature request related to a problem? Please describe.**
Customers would like to allowlist Some data to OpenSearch and send all discarded data to S3 Sink. Right now there is not an easy way to do it, it would be nice to add options of include_keys and exclude_keys under the sink.

**Describe the solution you'd like**
This additional options must be supported in OpenSearch sink and S3 sink, and can be extended to others as well.

The minimal usage is as below:
```
sink: 
  - opensearch:
     ...
      include_keys:  [ "key-one", "key-one" ]
            
  - opensearch:
     ...
      exclude_keys:  [ "key-three" ]

  - s3:
     ...
      exclude_keys:  [ "key-one", "key-one" ]

```

The assumption is that customers should not use both in the one sink. So if include_keys are defined, exclude_keys will be ignored.

For OpenSearch sink, this list of keys are under the document_root_key if document_root_key is defined.

It would be nice if create a list with name to be used as allowlist in one sink and reuse same name with negation as deny list in another sink. Such as: 

```
sink: 
  - opensearch:
      include_keys:
        waf_logs_desired : [ "key-one", "key-one" ] <<< This is like defining a list of Keys with name “waf_logs_desired” and to reuse same name in deny_list.
            
  - s3:
      exclude_keys: waf_logs_desired
```

### LINKED ISSUE #3080: PR feedback improvements from #2989
See PR comments in #2989.

### PR DESCRIPTION
**Pull request by daixba**
### Description
Add include_keys and exclude_keys to S3 sink (via ndjson codec), Also some inprovement and document updates as per PR comments.
 
### Issues Resolved
Resolve #3080 

Resolves #2975
 
### Check List
- [x] New functionality includes testing.
- [x] New functionality has been documented.
  - [x] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — CHANGES_REQUESTED** [review]
Thanks @daixba for adding the include/exclude keys to S3. In #2989, you made this feature on sinks in general. So the `s3` sink now includes `include_keys` and `exclude_keys`.

However, as you see in the implementation, the Codecs must implement them.

In this PR we currently have the possibility of:

```
sink:
- s3:
     include_keys: ["a", "b"]
     codec:
        newline:
          include_keys: ["c", "d"]
```

We should either:
* Remove the include_keys/exclude_keys from the core sink model and let sinks handle them according to how they handle the model; or
* Update this PR to use the include_keys/exclude_keys from the sink model.

**Comment by kkondaka** [comment]
I was looking at a sink codec recently and I think we have an issue here. Not just "include_keys/exclude_keys" but also with "tagsTargetKey" as well. We do not want both codec AND the sink to do this include/exclude_keys or tags resulting in duplicate data. Which means there should be one config (at the sink level) and a codec must handle these options. IF codec is not configured, only then Sink should take this configuration.

**Comment by daixba** [comment]
When I first submitted the PR for adding include_keys and exclude_keys, most of the output codec haven't been implemented yet, it's easy to change the codec definition to use the sink context.  But right now, all output codec have its own implementation of exclude_keys via config. Based on the current situation, what I submitted is the minmal change.

**Comment by daixba** [comment]
I raised the same at first in https://github.com/opensearch-project/data-prepper/pull/2989#discussion_r1269113614 which passed the codec the whole sink context via something like 
```
void start(OutputStream outputStream, SinkContext sinkContext) throws IOException;
```
So each codec don't need to add those duplicated configurations again. But right now I can't tell if this is still the right approach.  I am not sure if we plan to add the support of both included_keys and excluded_keys in every codec or not, so far I saw many of them has support of excluded_keys.

Based on the current situation, the minimal change is as per this PR and then raise another one to move the include_keys and exclude_keys out from sinkcontext and add them into the index configuration (similar to document root key) for OpenSearch sink, in this setting, most of the output codecs don't have to change.  

Please let me know the decision here.  Thanks.

**Comment by dlvenable** [comment]
I think we should aim for a configuration which looks like the following:

```
sink:
- s3:
     include_keys: ["a", "b"]
     codec:
        newline:
```

> Not just "include_keys/exclude_keys" but also with "tagsTargetKey" as well. We do not want both codec AND the sink to do this include/exclude_keys or tags resulting in duplicate data.

I think the sinks which use codecs should determine the values here, but not serialize them. This goes in line with the idea of an `OutputCodecContext` interface.

So the sink would be responsible for deciding:
* Which keys are included or excluded
* Which tags are added

The codec has to be responsible for serialization. But, it would just do as the sink tells it.

Would this address your concern @kkondaka ?

@daixba,

I do think in that PR we were discussing the idea of a context or options. We just need to nail the name down. But, the concept is applicable regardless.

```
interface OutputCodecContext {
  List<String> getIncludeKeys();
  List<String> getExcludeKeys();
  List<String> getTagsTargetKey();
```

Then on codec:

```
void writeEvent(Event event, OutputStream outputStream, OutputCodecContext outputCodecContext) throws IOException;
```


My point in the PR was that the codec should not be bound to the `SinkContext`. So the concept is similar, but it should have its own class. These may vary independently of each other.

**Comment by daixba** [comment]
I have submitted a new PR https://github.com/opensearch-project/data-prepper/pull/3122

Please ignore this one, once that one is resolved, this one will be closed.

Thanks.

**Comment by dlvenable** [comment]
@daixba , Are you good to close this PR?

**Pull request closed without merging**
