### PR TITLE
addressing build issue with s3-sink

### PR DESCRIPTION
**Pull request by cmanning09**
### Description
Addresses build failure observed in PR: https://github.com/opensearch-project/data-prepper/pull/2726

```
* What went wrong:
Execution failed for task ':data-prepper-plugins:s3-sink:spotlessMarkdownCheck'.
> The following files had format violations:
      README.md
          @@ -72,4 +72,3 @@
           ```
           ./gradlew·:data-prepper-plugins:s3-sink:integrationTest·-Dtests.s3sink.region=<your-aws-region>·-Dtests.s3sink.bucket=<your-bucket>
           ```
          -
  Run './gradlew :data-prepper-plugins:s3-sink:spotlessApply' to fix these violations.
```

See: https://github.com/opensearch-project/data-prepper/actions/runs/5082697390/jobs/9132752111?pr=2726
 
### Issues Resolved
None, pro-active clean up
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]
I think I addressed this in #2755, but as this has no conflicts it should be ok.

**Comment by dlvenable** [comment]
@cmanning09 , My `main` is passing. Maybe we should leave this be?

**Comment by cmanning09** [comment]
> @cmanning09 , My `main` is passing. Maybe we should leave this be?

@dlvenable , great. Thanks for addressing this. I will close this. At a high level are we not leveraging our approval workflows correctly? Ideally, this shouldn't have been committed and impacted other PRs.

**Comment by dlvenable** [comment]
@cmanning09 , I agree with that. We shouldn't have let that get through.

**Pull request closed without merging**
