### PR TITLE
MAINT: use os images in examples

### PR DESCRIPTION
**Pull request by chenqi0805**
### Description
This PR

(1) Updates opensearch and opensearch-dashboard images in examples/dev
(2) Fix some links in the sample app.
(2) Uploads opensearch build tar from maven local to help build data-prepper image as a workaround on `Gradle build daemon disappeared unexpectedly` in minikube docker
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chenqi0805** [comment]
Have not been able to make k8 works yet. It fails in local build OS step of `./build_images_for_minikube.sh`:
```
The message received from the daemon indicates that the daemon has disappeared.
Build request sent: Build{id=73cd4b02-7dbb-4164-acfc-23401ec94d8e, currentDir=/home/gradle/src/OpenSearch}
Attempting to read last messages from the daemon log...

Daemon pid: 103
  log file: /home/gradle/.gradle/daemon/6.6.1/daemon-103.out.log
----- Last  20 lines from daemon log file - daemon-103.out.log -----
Maven publication 'pluginMaven' pom metadata warnings (silence with 'suppressPomMetadataWarningsFor(variant)'):
  - Variant testFixturesApiElements:
      - Declares capability org.opensearch.gradle:build-tools-test-fixtures:1.0.0-alpha2 which cannot be mapped to Maven
  - Variant testFixturesRuntimeElements:
      - Declares capability org.opensearch.gradle:build-tools-test-fixtures:1.0.0-alpha2 which cannot be mapped to Maven
These issues indicate information that is lost in the published 'pom' metadata file, which may be an issue if the published library is consumed by an old Gradle version or Apache Maven.
The 'module' metadata file, which is used by Gradle 6+ is not affected.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 6.6.1
  OS Info               : Linux 5.10.25-linuxkit (amd64)
  JDK Version           : 14 (AdoptOpenJDK)
  JAVA_HOME             : /opt/java/openjdk
  Random Testing Seed   : 95E312D342EF1BD4
  In FIPS 140 mode      : false
=======================================
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/gradle/src/OpenSearch/buildSrc/src/main/java/org/opensearch/gradle/util/GradleUtils.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
----- End of the daemon log -----


FAILURE: Build failed with an exception.

* What went wrong:
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
The command '/bin/sh -c git clone https://github.com/opensearch-project/OpenSearch.git && cd OpenSearch && git checkout 1.0.0-alpha2 -b alpha2-release && ./gradlew publishToMavenLocal -Dbuild.version_qualifier=alpha2 -Dbuild.snapshot=false' returned a non-zero code: 1
```

**Comment by chenqi0805** [comment]
Resolved by uploading opensearch-build folder

**Review by wrijeff — DISMISSED** [review]
👍 - can be updated with the latest 1.0.0 OpenSearch docker images

**Review by wrijeff — APPROVED** [review]
👍

**Pull request merged**
