### PR TITLE
image name is wrong

### PR DESCRIPTION
**Pull request by subbusquareshift**
opensearchproject/opensearch-data-prepper to opensearchproject/data-prepper

### Description
[Describe what this change achieves]
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]

**Comment by dlvenable** [comment]
Thank you @subbusquareshift for catching and fixing this!

**Comment by dlvenable** [comment]
@subbusquareshift , This project requires a DCO on Git commit messages. Please see the following section for information on how to make your commit: https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md#developer-certificate-of-origin-dco

**Review by sshivanii — APPROVED** [review]

**Comment by dlvenable** [comment]
Since this PR does not have a DCO, I will be closing this PR.

**Comment by dlvenable** [comment]
We can fix this problem in another PR.

**Pull request closed without merging**
