### PR TITLE
Update PipelineModel to fix serialization

### PR DESCRIPTION
**Pull request by sshivanii**
Signed-off-by: Shivani Shukla <sshkamz@amazon.com>

### Description
Fixes serialization in `PipelineModel`
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [x] New functionality includes testing.
  - [x] All tests pass
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dlvenable** [comment]
Thanks! This is a good change. I think it might be good to test the serialization and deserialization since that is what caused the issue. But, I'm also happy to approve it as it is and come back to it.

**Comment by sshivanii** [comment]
> Thanks! This is a good change. I think it might be good to test the serialization and deserialization since that is what caused the issue. But, I'm also happy to approve it as it is and come back to it.

I'm creating a separate PR for `PipelinesDataFlowModel` with an object mapper which will test serialization. Do we want to test se/deserialization as part of `PipelineModelTest` too?

**Comment by dlvenable** [comment]
We can combine the tests into one if that works better.

**Review by dlvenable — APPROVED** [review]

**Review by chenqi0805 — APPROVED** [review]
changes look good to me. But is this PR just about renaming variables? I did not see how it fixes serialization.

**Comment by chenqi0805** [comment]
> changes look good to me. But is this PR just about renaming variables? I did not see how it fixes serialization.

Oh. Wait. I see those JsonProperty's. No issue.

**Comment by dlvenable** [comment]
It changes the serialization. Prior to this commit, Jackson would serialize these as:

```
sourcePluginModel:
  http:
prepperPluginModel:
  - grok:
sinkPluginModel:
  - opensearch:
```

**Pull request merged**
