### PR TITLE
MAINT: add codecov commenter bot

### PR DESCRIPTION
**Pull request by chenqi0805**
### Description
This PR

1. configured jacoco to generate xml report for codecov to identify
2. add codecov.yml config file
3. add codecov as an action in the github workflow
4. add codecov badge in project README
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed per the DCO using --signoff 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chenqi0805** [comment]
Blocking: We will need CODECOV_TOKEN to be added as secrets: https://app.codecov.io/gh/opensearch-project/data-prepper/

**Review by dblock — APPROVED** [review]

**Comment by dlvenable** [comment]
This looks very nice!

Can we move the file `codecov.yml` file into the `config/` directory? I'd like to try to avoid expanding our root directory.

**Comment by chenqi0805** [comment]
> Can we move the file codecov.yml file into the config/ directory? I'd like to try to avoid expanding our root directory.

@dlvenable According to https://docs.codecov.com/docs/codecov-yaml#can-i-name-the-file-codecovyml, I have moved it to .github

**Review by dlvenable — APPROVED** [review]

**Review by jianghancn — APPROVED** [review]

**Comment by chenqi0805** [comment]
@dlvenable @jianghancn Thanks!

**Pull request merged**
