### PR TITLE
#818: Moving to AWS SDK v2.

### LINKED ISSUE #818: Consolidate AWS SDK on v2
**Is your feature request related to a problem? Please describe.**

Data Prepper currently uses both the AWS Java SDK v1 and v2. It should use only one.

**Describe the solution you'd like**

Since v2 is the newer version, Data Prepper should use v2 exclusively.

### PR DESCRIPTION
**Pull request by jzonthemtn**
Signed-off-by: jzonthemtn <jzemerick@opensourceconnections.com>

### Description
Removes the AWS SDK v1 dependency. Updates the code using it to use AWS SDK v2 instead.

This pull request adds no new functionality. 

### Issues Resolved
#818 
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [X] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by sshivanii** [comment]
Thank you for your contribution! Currently, the Gradle build has one failing test so I'll investigate that further. Once all the checks pass, we're excited to merge in your work.

**Comment by jzonthemtn** [comment]
@sshivanii Thanks -- If I need to make any changes let me know!

**Comment by sshivanii** [comment]
@jzonthemtn There's a few Unused imports in `S3CertificateProvider.java` which is causing checkstyle errors, could you remove them? For your reference:
```
Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/s3/S3CertificateProvider.java:15:8: Unused import - software.amazon.awssdk.services.s3.S3Utilities. [UnusedImports]

Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/s3/S3CertificateProvider.java:18:8: Unused import - software.amazon.awssdk.services.s3.model.S3Object. [UnusedImports]
> Task :data-prepper-plugins:common:checkstyleMain FAILED

Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/common/src/main/java/com/amazon/dataprepper/plugins/certificate/s3/S3CertificateProvider.java:20:8: Unused import - java.net.MalformedURLException. [UnusedImports]
```

**Comment by jzonthemtn** [comment]
@sshivanii Sorry for missing those imports! Updated.

**Comment by sshivanii** [comment]
Thank you for making those changes! There's two more Unused imports causing a recent build failure, can you also remove them?
```
 Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProvider.java:13:8: Unused import - software.amazon.awssdk.services.acm.model.ExportCertificateRequest. [UnusedImports]
Error: eckstyle] [ERROR] /home/runner/work/data-prepper/data-prepper/data-prepper-plugins/peer-forwarder/src/main/java/com/amazon/dataprepper/plugins/prepper/peerforwarder/certificate/acm/ACMCertificateProvider.java:14:8: Unused import - software.amazon.awssdk.services.acm.model.ExportCertificateResponse. [UnusedImports]
```

**Comment by sshivanii** [comment]
We also wanted to know if you have done any manual testing, like an integration test with AWS?

**Comment by jzonthemtn** [comment]
I removed those two unused imports. I gave the other files a lookover and didn't see any others.

I have not done any manual testing. I wasn't entirely sure what checks/tests were run for PRs. I'm happy to stand things up if it's needed.

**Comment by dlvenable** [comment]
@jzonthemtn , Thanks for making this PR! It looks good to me. We just need to be sure it builds (I got that started) and we do need some integration testing of it. Right now, we don't have any test suites that connect to AWS services, so none of these are part of the test suite. I believe that @sshivanii is setting up an environment that uses AWS for credentials to test the changes manually.

Really, we should have some automated integration tests that can run as GHA to verify changes like this going forward, but unfortunately they are not currently covered.

**Comment by jzonthemtn** [comment]
@dlvenable Sounds great. If those integration tests get on the roadmap I'd be happy to help get them wired up.

**Review by dlvenable — APPROVED** [review]

**Comment by sshivanii** [comment]
Thank you for this PR! We did some manual testing with the certificates stored locally, in S3 and using ACM and they worked perfectly fine.

**Review by sshivanii — APPROVED** [review]

**Comment by dlvenable** [comment]
@jzonthemtn , Thank you again for this contribution! I created #1481 as an issue to track adding integration tests or end-to-end tests which verify that these AWS integrations continue to work. This will be probably be more involved than the previous AWS SDK migration, but if you are interested, I'd be happy to accept a PR, and could discuss some approaches in advance in the issue.

**Pull request merged**
