### PR TITLE
Support Mutual TLS authentication for Core Peer Forwarding

### LINKED ISSUE #1758: Support mTLS authentication between peers for core peer-forwarding

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Adds an option to support either Mutual TLS or Unauthenticated access in Core Peer Forwarding. In this PR, the default is unauthenticated. We can swap the default to mTLS once we enable SSL-by-default in #1699.
 
### Issues Resolved

Resolves #1758
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by deepdatta — APPROVED** [review]
looks good

**Review by asifsmohammed — DISMISSED** [review]
LGTM

**Comment by dlvenable** [comment]
Tests are failing. I'm going to rebase from main after merging in #1777.

**Comment by dlvenable** [comment]
@asifsmohammed , @deepdatta ,

I rebased this with `main`. There were some conflicts in `PeerForwarder_ClientServerIT`, but they were all related to updating reading the buffer to get `Record<Event>` instead of `Record<?>`.

It is ready for another review.

**Review by asifsmohammed — APPROVED** [review]
Thanks David for working on this and fixing build failure.

**Review by deepdatta — APPROVED** [review]

**Pull request merged**
