### PR TITLE
Added support for 'epoch_micro' in date processor

### LINKED ISSUE #4076: Support epoch_micro in date processor patterns
**Is your feature request related to a problem? Please describe.**
We do support epoch_second, epoch_mili and epoch_nano, but noticed some users need epoch_micro as well. 

We have a workaround using `value_expression` in `add_entires` to convert micro seconds to other format we support. But we might as well add this `epoch_micro` option to save the need for an additional processor.

**Describe the solution you'd like**
Support epoch_micro in date processor patterns

**Describe alternatives you've considered (Optional)**
Use `value_expression` in `add_entires` to convert micro seconds to other format we support

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Utkarsh-Aga**
### Description
Added support for `epoch_micro` in date processor
 
### Issues Resolved
Resolves #4076 
 
### Check List
- [x] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
- [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by oeyh — COMMENTED** [review]
Thanks for the PR! 

Looks good overall. Can you also update `DateProcessorTests` class to include tests for epoch_micro?

**Comment by Utkarsh-Aga** [comment]
Okay Sure, will do that.

**Comment by Utkarsh-Aga** [comment]
Hello @oeyh,
I have added test in `DateProcessorTests`, would request you to please review.

**Review by oeyh — APPROVED** [review]
Nice, thanks!

**Review by kkondaka — APPROVED** [review]

**Comment by serveder02** [comment]
Hello @oeyh! When you are going to make a release with this feature?
I did not find this changes in version 2.6.2

**Comment by dlvenable** [comment]
@serveder02 , This feature will be available in Data Prepper 2.7.0. The recent 2.6.2 release has bug fixes and security improvements only.

**Pull request merged**
