### PR TITLE
Updated the readme for opensearch plugin to use date processor in combination with Opensearch sink

### PR DESCRIPTION
**Pull request by akshay0709**
### Description

Updated the readme with example for opensearch plugin to use date processor in combination with openaearch sink to ingest into indices based on the timestamp from a field of the incoming record.
 
### Issues Resolved
https://github.com/opensearch-project/data-prepper/issues/4832
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dlvenable — APPROVED** [review]
Thank you @akshay0709 for this contribution!

**Comment by akshay0709** [comment]
@dlvenable I forgot to sign the DCO in my first commit. Is it required for the PR to be merged? Should I push an additional commit with the DCO?

**Comment by dlvenable** [comment]
@akshay0709 , Yes, we do require the DCO per the OpenSearch project policy. You can add the DCO and then force push your commit(s).

**Comment by akshay0709** [comment]
@dlvenable I pushed an empty commit with DCO. Let me know if this works.

**Comment by dlvenable** [comment]
@akshay0709 , Thank you. The original commit is also missing the sign-off. These steps should resolve it:

```
git rebase HEAD~2 --signoff
git push --force-with-lease origin update-doc-date-processor
```

**Comment by akshay0709** [comment]
@dlvenable Done

**Review by chenqi0805 — APPROVED** [review]

**Pull request merged**
