### PR TITLE
Use a Protobuf buffer message for data in the Kafka buffer

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

This change adds a new `KafkaBufferMessage` Protobuf message for data stored in the Kafka topic. This PR adds this as a wrapper around the data. It does not include the encrypted data key yet. See #3620 for some context.
 
### Issues Resolved

None.

Contributes toward #3620.
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has a documentation issue. Please link to it in this PR.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by engechas — DISMISSED** [review]

**Review by hshardeesi — APPROVED** [review]

**Comment by dlvenable** [comment]
I found a problem with the current testing in the `KafkaBufferIT` class. It was mocking the configs, which also meant that they were using JSON serialization which is not supported by the `kafka` buffer. I pushed a new commit which resolves this issue. This also found that there are some issues with the serialization for non-bytes in the buffer.

Additionally, I added some new integration tests to verify writing raw bytes and verifying the underlying format in the topic.

**Comment by kkondaka** [comment]
@dlvenable don't we need to do serialization in kafka producer and deserialization in kafka consumer? These may be no-ops now but I thought we need them in the code.

**Comment by dlvenable** [comment]
> @dlvenable don't we need to do serialization in kafka producer and deserialization in kafka consumer? These may be no-ops now but I thought we need them in the code.

I added these:

https://github.com/opensearch-project/data-prepper/pull/3635/files#diff-8dd74d75ec6523d0cdfdd659bc48ebfb7e9373ec10212d042ab508276c4786c8R120-R121

https://github.com/opensearch-project/data-prepper/pull/3635/files#diff-52a4451703d806af27981df4b0f7a94bac8373c36a240934c2e49dd282ddb680R450-R454

**Comment by kkondaka** [comment]
@dlvenable I understand that. But I am wondering if we need serialization and deserialization for other paths - especially - the `writeBytes` path

**Comment by dlvenable** [comment]
@kkondaka , The new `Serializer` and `Deserializer` are provided to the Kafka producer and consumer. So they apply to all data produced or consumed. And it is included in the `writeBytes` path.

**Review by engechas — APPROVED** [review]

**Review by kkondaka — APPROVED** [review]

**Pull request merged**
