### PR TITLE
MOD: fix typos 

### PR DESCRIPTION
**Pull request by rmarasigan**
### Description
Fix Documentation Overview
* Link
* Typo

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on the following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

Signed-off-by:  Shanelle Marasigan

### CODE REVIEW

**Comment by oeyh** [comment]
@rmarasigan Thanks for the PR!
It fails the DCO check because the commit is not signed off. You can amend your commit and add a line in this format with your info in the commit message: `Signed-off-by: Jane Smith <jane.smith@email.com>` and do a force push to fix it. (Please refer to `https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md)

**Comment by rmarasigan** [comment]
> @rmarasigan Thanks for the PR!
> It fails the DCO check because the commit is not signed off. You can amend your commit locally and add a line in this format with your name and email in the commit message: `Signed-off-by: Jane Smith <jane.smith@email.com>` and do a force push to fix it. (Please refer to `https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md)

Hello, @oeyh, I already fixed the commit message and added the `Signed-off-by`.

Thanks!

**Review by oeyh — APPROVED** [review]
Looks good!

**Review by JonahCalvo — APPROVED** [review]

**Comment by JonahCalvo** [comment]
Good stuff :)

**Pull request merged**
