### PR TITLE
Remove the macOS build from the distributions build

### PR DESCRIPTION
**Pull request by dlvenable**
### Description

Data Prepper is not currently releasing a macOS archive for Data Prepper. This PR removes the macOS archive build to speed up the build process. We can add it back later if we decide to build a macOS distribution.
 
### Issues Resolved

Contributes to #977
 
### Check List
- [ ] New functionality includes testing.
- [x] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [x] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by graytaylor0** [comment]
What is the time difference in the build process with and without the MacOS archive?

**Comment by dlvenable** [comment]
> What is the time difference in the build process with and without the MacOS archive?

I'm not completely certain of the build time. But, all the archives need to be uploaded. It takes about 1-2 minutes per archive on my machine to upload each. So that should cut off at least 4-8 minutes.

**Comment by dlvenable** [comment]
The other reason to remove these archives is that we don't test them. The `uploadArchives` Gradle task will upload these to our staging S3 bucket. But, since we don't test them, we'd be putting out these untested archives for possible downloads.

**Review by graytaylor0 — APPROVED** [review]

**Review by sshivanii — APPROVED** [review]
LGTM

**Pull request merged**
