### PR TITLE
Update HTTP source ssl validations

### PR DESCRIPTION
**Pull request by asifsmohammed**
Signed-off-by: Asif Sohail Mohammed <nsifmoh@amazon.com>

### Description
Updated validations which require to define certificate and key file when using ACM for ssl.
 
### Issues Resolved
[List any issues this PR will resolve]
 
### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
- [ ] Commits are signed with a real name per the DCO

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/data-prepper/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by dinujoh — APPROVED** [review]

**Review by sbayer55 — APPROVED** [review]

**Comment by dlvenable** [comment]
@asifsmohammed, Similar to my question in #1731: Should we backport these?

**Comment by dlvenable** [comment]
It appears that #1678 was not backported, so I think this one would not be either.

**Comment by asifsmohammed** [comment]
As mentioned in #1731, this is a new features to support ACM and S3 for certificates for SSL. We don't have to backport and add it as part of 2.0 release.

**Comment by dlvenable** [comment]
Yes, I agree, these features were not backported, so there is no need to backport the bug fixes. Thanks!

**Pull request merged**
